{"uuid": "9f56746a-44ef-4724-848c-2e45d9de02e0", "children": ["2c1f671c-0a09-4566-a2e1-2504489fb188"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist\nStacktrace:\n\tGetHandleVerifier [0x0030E123+48179]\n\t(No symbol) [0x00295D01]\n\t(No symbol) [0x0017D72D]\n\t(No symbol) [0x001A808E]\n\t(No symbol) [0x001A3C80]\n\t(No symbol) [0x001A0A69]\n\t(No symbol) [0x001DCA51]\n\t(No symbol) [0x001DC5FA]\n\t(No symbol) [0x001D3A26]\n\t(No symbol) [0x001AB7BC]\n\t(No symbol) [0x001AC62D]\n\tGetHandleVerifier [0x00627C33+3299139]\n\tGetHandleVerifier [0x00665BF2+3553026]\n\tGetHandleVerifier [0x00660BCC+3532508]\n\tGetHandleVerifier [0x003A494E+664670]\n\t(No symbol) [0x002A0AB4]\n\t(No symbol) [0x0029BF08]\n\t(No symbol) [0x0029C02D]\n\t(No symbol) [0x0028DD00]\n\tBaseThreadInitThunk [0x756B6839+25]\n\tRtlGetFullPathName_UEx [0x7769906F+1215]\n\tRtlGetFullPathName_UEx [0x7769903D+1165]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\testcases\\conftest.py\", line 25, in setup\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 209, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 293, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708519139827, "stop": 1708519262423}], "start": 1708519139827, "stop": 1708519270360}